In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('players_fifa23.csv')

In [ ]:
df.head()

,ID,Name,FullName,Age,Height,Weight,PhotoUrl,Nationality,Overall,Potential,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,158023,L. Messi,Lionel Messi,35,169,67,https://cdn.sofifa.net/players/158/023/23_60.png,Argentina,91,91,...,91,88,91,67,66,67,62,53,62,22
1,165153,K. Benzema,Karim Benzema,34,185,81,https://cdn.sofifa.net/players/165/153/23_60.png,France,91,91,...,89,84,89,67,67,67,63,58,63,21
2,188545,R. Lewandowski,Robert Lewandowski,33,185,81,https://cdn.sofifa.net/players/188/545/23_60.png,Poland,91,91,...,86,83,86,67,69,67,64,63,64,22
3,192985,K. De Bruyne,Kevin De Bruyne,31,181,70,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,91,91,...,91,91,91,82,82,82,78,72,78,24
4,231747,K. Mbappé,Kylian Mbappé,23,182,73,https://cdn.sofifa.net/players/231/747/23_60.png,France,91,95,...,92,84,92,70,66,70,66,57,66,21

In [ ]:
df.describe()

,ID,Age,Height,Weight,Overall,Potential,Growth,TotalStats,BaseStats,ValueEUR,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
count,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,1.853900e+04,...,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000,18539.000000
mean,237011.899725,25.240412,181.550839,75.173904,65.852042,71.016668,5.164626,1602.114569,357.946221,2.875461e+06,...,58.451319,57.374076,58.451319,56.281569,55.928583,56.281569,55.650251,54.528184,55.650251,23.257134
std,26714.860353,4.718163,6.858097,7.013593,6.788353,6.192866,5.374795,273.160237,39.628259,7.635129e+06,...,13.987122,13.171194,13.987122,13.903836,13.872190,13.903836,14.159466,14.743929,14.159466,15.108925
min,1179.000000,16.000000,155.000000,49.000000,47.000000,48.000000,0.000000,759.000000,224.000000,0.000000e+00,...,18.000000,18.000000,18.000000,17.000000,19.000000,17.000000,17.000000,18.000000,17.000000,10.000000
25%,221663.000000,21.000000,177.000000,70.000000,62.000000,67.000000,0.000000,1470.000000,331.000000,4.750000e+05,...,54.000000,53.000000,54.000000,51.000000,48.000000,51.000000,49.000000,45.000000,49.000000,17.000000
50%,241195.000000,25.000000,182.000000,75.000000,66.000000,71.000000,4.000000,1640.000000,358.000000,1.000000e+06,...,62.000000,60.000000,62.000000,59.000000,59.000000,59.000000,59.000000,58.000000,59.000000,18.000000
75%,259059.000000,29.000000,186.000000,80.000000,70.000000,75.000000,9.000000,1786.000000,385.000000,2.000000e+06,...,67.000000,66.000000,67.000000,66.000000,66.000000,66.000000,65.000000,66.000000,65.000000,20.000000
max,271817.000000,44.000000,206.000000,105.000000,91.000000,95.000000,26.000000,2312.000000,502.000000,1.905000e+08,...,92.000000,91.000000,92.000000,88.000000,89.000000,88.000000,87.000000,90.000000,87.000000,90.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18539 entries, 0 to 18538
Data columns (total 90 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 18539 non-null  int64
 1   Name               18539 non-null  object
 2   FullName           18539 non-null  object
 3   Age                18539 non-null  int64
 4   Height             18539 non-null  int64
 5   Weight             18539 non-null  int64
 6   PhotoUrl           18539 non-null  object
 7   Nationality        18539 non-null  object
 8   Overall            18539 non-null  int64
 9   Potential          18539 non-null  int64
 10  Growth             18539 non-null  int64
 11  TotalStats         18539 non-null  int64
 12  BaseStats          18539 non-null  int64
 13  Positions          18539 non-null  object
 14  BestPosition       18539 non-null  object
 15  Club               18539 non-null  object
 16  ValueEUR           18539 non-null  int64
 17  WageEUR            18539 non-null  int64
 18  ReleaseClause      18539 non-null  int64
 19  ClubPosition       18447 non-null  object
 20  ContractUntil      18447 non-null  float64
 21  ClubNumber         18447 non-null  float64
 22  ClubJoined         18539 non-null  int64
 23  OnLoad             18539 non-null  bool
 24  NationalTeam       18539 non-null  object
 25  NationalPosition   817 non-null    object
 26  NationalNumber     817 non-null    float64
 27  PreferredFoot      18539 non-null  object
 28  IntReputation      18539 non-null  int64
 29  WeakFoot           18539 non-null  int64
 30  SkillMoves         18539 non-null  int64
 31  AttackingWorkRate  18539 non-null  object
 32  DefensiveWorkRate  18539 non-null  object
 33  PaceTotal          18539 non-null  int64
 34  ShootingTotal      18539 non-null  int64
 35  PassingTotal       18539 non-null  int64
 36  DribblingTotal     18539 non-null  int64
 37  DefendingTotal     18539 non-null  int64
 38  PhysicalityTotal   18539 non-null  int64
 39  Crossing           18539 non-null  int64
 40  Finishing          18539 non-null  int64
 41  HeadingAccuracy    18539 non-null  int64
 42  ShortPassing       18539 non-null  int64
 43  Volleys            18539 non-null  int64
 44  Dribbling          18539 non-null  int64
 45  Curve              18539 non-null  int64
 46  FKAccuracy         18539 non-null  int64
 47  LongPassing        18539 non-null  int64
 48  BallControl        18539 non-null  int64
 49  Acceleration       18539 non-null  int64
 50  SprintSpeed        18539 non-null  int64
 51  Agility            18539 non-null  int64
 52  Reactions          18539 non-null  int64
 53  Balance            18539 non-null  int64
 54  ShotPower          18539 non-null  int64
 55  Jumping            18539 non-null  int64
 56  Stamina            18539 non-null  int64
 57  Strength           18539 non-null  int64
 58  LongShots          18539 non-null  int64
 59  Aggression         18539 non-null  int64
 60  Interceptions      18539 non-null  int64
 61  Positioning        18539 non-null  int64
 62  Vision             18539 non-null  int64
 63  Penalties          18539 non-null  int64
 64  Composure          18539 non-null  int64
 65  Marking            18539 non-null  int64
 66  StandingTackle     18539 non-null  int64
 67  SlidingTackle      18539 non-null  int64
 68  GKDiving           18539 non-null  int64
 69  GKHandling         18539 non-null  int64
 70  GKKicking          18539 non-null  int64
 71  GKPositioning      18539 non-null  int64
 72  GKReflexes         18539 non-null  int64
 73  STRating           18539 non-null  int64
 74  LWRating           18539 non-null  int64
 75  LFRating           18539 non-null  int64
 76  CFRating           18539 non-null  int64
 77  RFRating           18539 non-null  int64
 78  RWRating           18539 non-null  int64
 79  CAMRating          18539 non-null  int64
 80  LMRating           18539 non-null  int64
 81  CMRating           18539 non-null  int64
 82  RMRating           18539 non-null  int64
 83  LWBRating          18539 non-null  int64
 84  CDMRating          18539 non-null  int64
 85  RWBRating          18539 non-null  int64
 86  LBRating           18539 non-null  int64
 87  CBRating           18539 non-null  int64
 88  RBRating           18539 non-null  int64
 89  GKRating           18539 non-null  int64
dtypes: bool(1), float64(3), int64(73), object(13)
memory usage: 12.6+ MB

In [ ]:

needed_colums = ['ID', 'Name', 'Age', 'Height', 'Weight',
       'Overall', 'Potential', 'Growth', 'TotalStats',
       'BaseStats', 'BestPosition', 'Club', 'ValueEUR', 'WageEUR',
       'ReleaseClause', 'ContractUntil', 'ClubJoined', 'OnLoad',
       'PreferredFoot', 'IntReputation', 'WeakFoot','Nationality',
       'SkillMoves', 'AttackingWorkRate', 'DefensiveWorkRate', 'PaceTotal',
       'ShootingTotal', 'PassingTotal', 'DribblingTotal', 'DefendingTotal',
       'PhysicalityTotal', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes']

       data = data[needed_colums]